### ISSUE TITLE
pull request

### ISSUE THREAD

**Issue by Gilmoursa** [learn-co-curriculum/pass-by-reference#14]
I don't think this exercise should have a pull request. There's no programming exercise or ruby file to make changes to.

**Comment by AnnJohn** [comment]
Hi @Gilmoursa thank you for raising the issue. As a suggestion, please review open pull requests to make sure that you're not replicating an issue that already exists. Since this looks like an issue that has already been raised, I'm going to close this one and reference it in the other one. But please keep reviewing our curriculum and making issues!
